apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
        - name: tls-secret
          mountPath: /etc/nginx/ssl
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf
      - name: git-sync
        image: registry.k8s.io/git-sync/git-sync:v4.2.0
        env:
        - name: GIT_SYNC_REPO
          value: "https://github.com/CarmineN00/CarmineN00.github.io"
        - name: GIT_SYNC_DEST
          value: "portfolio"
        - name: GIT_SYNC_ROOT
          value: "/git"
        - name: GIT_SYNC_ONE_TIME
          value: "false"
        volumeMounts:
        - name: html-volume
          mountPath: /git
      volumes:
      - name: html-volume
        emptyDir: {}
      - name: tls-secret
        secret:
          secretName: tls-secret
      - name: nginx-config
        configMap:
          name: nginx-config
